# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available
resolver: lts-13.0

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver
extra-deps:
- RSA-2.2.0
- authenticate-oauth-1.5.1.2
- heroku-0.1.2.3
- heroku-persistent-0.2.0
- load-env-0.2.0.2
- tld-0.3.0.2
- unliftio-0.2.9.0
- yesod-auth-oauth-1.6.0.1

# Override default flag values for local packages and extra-deps
flags:
  croniker:
    library-only: false
    dev: false

# Extra package databases containing global packages
extra-package-dbs: []
